name: pytorch_me
channels:
#  - postelrich
  - conda-forge
dependencies:
  - python>=3.6
  - numpy
  - matplotlib
  - pandas
  - pip
  - pip:
    - vtk
    - git+https://github.com/erosmontin/pynico
    - git+https://github.com/erosmontin/pyable
